name: NodeJs CI

on :
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name : Using Nodejs
      uses : action/setup-node@v2
      with:
        node-version: 16.x
    - run: npm i
    - run: npm run build
