name: Deploy code to production
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Copy Code to VPS
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          source: "."
          target: "/home/dev/Web/frontend"
        
      - name: Build and Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: sh build.sh
