name: Deploy
on:
  push:
    brances: [master]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Accesing Server & Deploy App
        uses: appleboy/ssh-action@v0.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSHKEY}}
          port: ${{secrets.PORT}}
          script: |
            cd /home/son/Web/lb/frontend
            git pull origin master
            rm -rf package-lock.json
            npm install
            npm run build
            pm2 restart frontend
