name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name : setup node env
        uses : action/setup-node@2.1.5
        with:
          node-version: 16
          check-latest: true
          
      - name : Install Dependencies
        run : yarn
      
      - name: Copy content via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "."
          target: "/home/dev/Web/frontend"

      - name: Accesing Server & Deploy App
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSHKEY}}
          port: ${{secrets.PORT}}
          script: |
            cd /home/dev/Web/frontend
            rm -rf package-lock.json
            yarn install
            yarn build
            pm2 restart frontend
