name: Deploy code to production
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Copy Code to VPS
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@master
      - name: "Setup NodeJS"
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      
      
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          source: "."
          target: "/home/dev/Web/frontend"
        
      - name: Restarting Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: sh ../../build.sh
